CLUSTER = False
SMALL_DATASET = True
DAYS_PER_MONTH = 1 # 'MAX'
SIZE = ['small'] # 'large'
DATA_SOURCES = ['roundshot'] # 'panomax'
IMAGES_PER_DAY = 32
PATCH_SIZE = (128, 128) # height, width
NUM_CHANNELS = 3 # RGB
BATCH_SIZE = 2
NUM_LOADER_WORKERS = 8
EPOCHS = 2

SPLIT_TOTAL = 100
SPLIT_TRAIN = 79
SPLIT_TEST = 89
SPLIT_VALID = 99


