CLUSTER = False
DAYS_PER_MONTH = 2 # 'MAX'
SIZE = ['small'] # 'large'
DATA_SOURCES = ['roundshot'] # 'panomax'
IMAGES_PER_DAY = 32
PATCH_SIZE = (128, 128) # height, width
NUM_CHANNELS = 3 # BGR
BATCH_SIZE = 10
NUM_LOADER_WORKERS = 8

SPLIT_TOTAL = 10
SPLIT_TRAIN = 7
SPLIT_TEST = 8
SPLIT_VALID = 9


